PACKAGE_NAME="aic8800"
PACKAGE_VERSION="1.2.0"
BUILT_MODULE_NAME[0]="aic_load_fw"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless/aic8800"
BUILT_MODULE_NAME[1]="aic8800_fdrv"
DEST_MODULE_LOCATION[1]="/kernel/drivers/net/wireless/aic8800"
MAKE="make KVER=${kernelver}"
CLEAN="make clean"
AUTOINSTALL="yes"
